#!/bin/bash
# Author: Roger Tu
# Date: 2012-08-15

# NOTE: Not a good idea to do searches consisting of single digit numbers

export BOLD_FONT=`tput bold`
export RESET_ALL="\e[0m"
export REVERSE=`tput rev`

export FOREGROUND_BLACK=`tput setaf 0`
export FOREGROUND_RED=`tput setaf 1`
export FOREGROUND_GREEN=`tput setaf 2`
export FOREGROUND_YELLOW=`tput setaf 3`
export FOREGROUND_BLUE=`tput setaf 4`
export FOREGROUND_PURPLE=`tput setaf 5`
export FOREGROUND_CYAN=`tput setaf 6`
export FOREGROUND_WHITE=`tput setaf 7`
export FOREGROUND_ORANGE=`tput setaf 202`

trap reset_highlight_colors SIGINT
function reset_highlight_colors
{
    tput sgr0
}

function print_help
{
    echo "Usage: highlight [-x] <color_flag> <search_string> [. . .]
        Normal color flags:
            -k normal black
            -r normal red
            -g normal green
            -y normal yellow
            -b normal blue
            -p normal purple
            -c normal cyan
            -w normal white
        Bold color flags:
            -K bold black
            -R bold red
            -G bold green
            -Y bold yellow
            -B bold blue
            -P bold purple
            -C bold cyan
            -W bold white
        Other colors flags (Must have 256-color terminal enabled):
            -o normal orange
            -O bold orange
        Optional modifiers:
            -i inverse mode
            -x do not reset formatting at end of line"

    exit 1
}

function print_error
{
    echo "Error: -${OPTARG} requires a search string" >&2
    exit 1
}

if [ $# -eq 0 ]
then
    print_help
fi

REPLACEMENT_PREFIX='s/'
REPLACEMENT_DELIMITER='/'
REPLACEMENT_POSTFIX='/g;'

FULL_REPLACEMENT_STRING=''

while getopts ':ixk:K:r:R:g:G:y:Y:b:B:p:P:c:C:w:W:o:O:' COLOR
do
    SEARCH_STRING=''
    COLOR_STRING='$&'

    BLEED_JUST_SET=""
    INVERSE_JUST_SET=""

    case ${COLOR} in
        x)
            BLEED_MODE=0
            BLEED_JUST_SET=0
            ;;
        i)
            INVERSE_MODE=0
            INVERSE_JUST_SET=0
            ;;
        k)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_BLACK}$&${RESET_ALL}"
            ;;
        K)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_BLACK}$&${RESET_ALL}"
            ;;
        r)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_RED}$&${RESET_ALL}"
            ;;
        R)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_RED}$&${RESET_ALL}"
            ;;
        g)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_GREEN}$&${RESET_ALL}"
            ;;
        G)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_GREEN}$&${RESET_ALL}"
            ;;
        y)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_YELLOW}$&${RESET_ALL}"
            ;;
        Y)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_YELLOW}$&${RESET_ALL}"
            ;;
        b)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_BLUE}$&${RESET_ALL}"
            ;;
        B)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_BLUE}$&${RESET_ALL}"
            ;;
        p)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_PURPLE}$&${RESET_ALL}"
            ;;
        P)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_PURPLE}$&${RESET_ALL}"
            ;;
        c)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_CYAN}$&${RESET_ALL}"
            ;;
        C)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_CYAN}$&${RESET_ALL}"
            ;;
        w)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_WHITE}$&${RESET_ALL}"
            ;;
        W)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_WHITE}$&${RESET_ALL}"
            ;;
        o)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${FOREGROUND_ORANGE}$&${RESET_ALL}"
            ;;
        O)
            SEARCH_STRING=${OPTARG}
            COLOR_STRING="${BOLD_FONT}${FOREGROUND_ORANGE}$&${RESET_ALL}"
            ;;
        \?)
            print_help
            ;;
        :)
            print_error
            ;;
    esac

    if [ -z "${BLEED_JUST_SET}" -o -z "${INVERSE_JUST_SET}" ]
    then
        # Build up the whole replacement string
        FULL_REPLACEMENT_STRING="${FULL_REPLACEMENT_STRING}${REPLACEMENT_PREFIX}${SEARCH_STRING}${REPLACEMENT_DELIMITER}${COLOR_STRING}${REPLACEMENT_POSTFIX}"
    fi
done
shift $(($OPTIND-1))

if [ $# -gt 0 ];
then
    echo 'this is happening?'
    print_help
fi

if [ -n "${BLEED_MODE}" ]
then
    FULL_REPLACEMENT_STRING=$(echo "${FULL_REPLACEMENT_STRING}" | perl -pe 's/\\e\[0m//g')
fi
if [ -n "${INVERSE_MODE}" ]
then
    FULL_REPLACEMENT_STRING="${REVERSE}${FULL_REPLACEMENT_STRING}"
fi

perl -pe "${FULL_REPLACEMENT_STRING}"
reset_highlight_colors

